### ISSUE TITLE
Typo!

### ISSUE THREAD

**Issue by KFad11** [learn-co-curriculum/phrg-what-makes-the-web-possible#2]
"e" s/b "be". 
<img width="661" alt="Screen Shot 2019-03-12 at 9 31 02 AM" src="https://user-images.githubusercontent.com/48073883/54203980-b34f6f00-44a9-11e9-9e36-cc9b54cff1a6.png">

**Comment by KFad11** [comment]
@garettarrowood

**Comment by KFad11** [comment]
"Let" s/b "Let's"
<img width="659" alt="Screen Shot 2019-03-12 at 9 34 02 AM" src="https://user-images.githubusercontent.com/48073883/54204179-13deac00-44aa-11e9-9294-ed698563cc00.png">

**Comment by KFad11** [comment]
<img width="448" alt="Screen Shot 2019-03-12 at 9 37 12 AM" src="https://user-images.githubusercontent.com/48073883/54204381-88194f80-44aa-11e9-93c6-6a3deb2a68d8.png">

**Comment by garettarrowood** [comment]
Resolved in #3
